name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: Backport
        uses: VachaShah/backport@v2.0.0
        with:
          github_token: ${{ secrets.APP_PRIVATE_KEY }}
          branch_name: backport/backport-${{ github.event.number }}
          files_to_skip: 'CHANGELOG.md'
