name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: Backport
        id: backport
        uses: VachaShah/backport@v2.1.0
        with:
          github_token: ${{ secrets.APP_PRIVATE_KEY }}
          branch_name: backport/backport-<%= number %>-to-<%= base %>
          files_to_skip: 'CHANGELOG.md'
      - name: Print output
          run: echo "${{ backport.created_pull_requests }}"
