name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Backport
        uses: VachaShah/backport@v2.2.0
        with:
          github_token: ${{ secrets.TEST_KEY }}
          head_template: backport/backport-<%= number %>-to-<%= base %>
          failure_labels: backport-failed
          files_to_skip: 'CHANGELOG.md'
