name: "Changelog Verifier"
on:
  pull_request:
    types: [opened, edited, review_requested, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  verify-changelog:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: GitHub App token
        id: github_app_token
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: dangoslen/dependabot-changelog-helper@v1
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          version: 'Unreleased'

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          commit_message: "Update changelog"
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'

      - uses: dangoslen/changelog-enforcer@v3
